### ISSUE TITLE
Is this production-usable?

### ISSUE THREAD

**Issue by tgoldenberg** [davibe/next.js-example-with-global-stylesheet#1]
I've really wanted to use something like this (`.scss`) in next.js. While it is working fine for me in development, I'm not able to deploy via either `now` or heroku. Am I missing something?

**Comment by tgoldenberg** [comment]
Here is the log that I'm getting, pointing to a dependency of `node-sass`

```
Counting objects: 471, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (274/274), done.
Writing objects: 100% (471/471), 10.93 MiB | 0 bytes/s, done.
Total 471 (delta 163), reused 471 (delta 163)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  6.9.x
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 6.9.x via semver.io...
remote:        Downloading and installing node 6.9.5...
remote:        Using default npm version: 3.10.10
remote:        Resolving yarn version (latest) via semver.io...
remote:        Downloading and installing yarn (0.19.1)...
remote:        Installed yarn 0.19.1
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v0.19.1
remote:        warning commandiv-next@1.0.0: No license field
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        warning fsevents@1.0.17: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning "material-ui@0.16.7" has unmet peer dependency "react@^15.0.0".
remote:        warning "material-ui@0.16.7" has unmet peer dependency "react-dom@^15.0.0".
remote:        warning "react-addons-css-transition-group@15.4.2" has unmet peer dependency "react@^15.4.2".
remote:        warning "react-addons-pure-render-mixin@15.4.2" has unmet peer dependency "react@^15.4.2".
remote:        warning "react-addons-transition-group@15.4.2" has unmet peer dependency "react@^15.4.2".
remote:        warning "react-ga@2.1.2" has unmet peer dependency "react@>= 0.14.0".
remote:        warning "react-redux@5.0.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0".
remote:        warning "react-social-icons@2.5.1" has unmet peer dependency "react@0.13.x || 0.14.x || 15.x.x".
remote:        warning "react-tap-event-plugin@2.0.1" has unmet peer dependency "react@^15.4.0-0".
remote:        warning "react-tap-event-plugin@2.0.1" has unmet peer dependency "react-dom@^15.4.0-0".
remote:        warning "react-test-renderer@15.4.2" has unmet peer dependency "react@^15.4.2".
remote:        warning "request-promise@4.1.1" has unmet peer dependency "request@^2.34".
remote:        warning "enzyme@2.7.1" has unmet peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x".
remote:        warning "eslint-config-airbnb@14.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^3.0.2".
remote:        warning "react-addons-test-utils@15.4.2" has unmet peer dependency "react-dom@^15.4.2".
remote:        warning "react-addons-create-fragment@15.4.2" has unmet peer dependency "react@^15.4.2".
remote:        warning "react-event-listener@0.4.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
remote:        warning "recompose@0.21.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
remote:        warning "glob-promise@3.1.0" has unmet peer dependency "glob@*".
remote:        warning "request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
remote:        warning "react-addons-shallow-compare@15.4.2" has unmet peer dependency "react@^15.4.2".
remote:        [4/4] Building fresh packages...
remote:        error /tmp/build_d029c2febc1da654477c5754a5416775/node_modules/node-sass: Command failed.
remote:        Exit code: 1
remote:        Command: sh
remote:        Arguments: -c node scripts/install.js
remote:        Directory: /tmp/build_d029c2febc1da654477c5754a5416775/node_modules/node-sass
remote:        Output:
remote:        module.js:471
remote:        throw err;
remote:        ^
remote:
remote:        Error: Cannot find module 'code-point-at'
remote:        at Function.Module._resolveFilename (module.js:469:15)
remote:        at Function.Module._load (module.js:417:25)
remote:        at Module.require (module.js:497:17)
remote:        at require (internal/module.js:20:19)
remote:        at Object.<anonymous> (/tmp/build_d029c2febc1da654477c5754a5416775/node_modules/string-width/index.js:3:19)
remote:        at Module._compile (module.js:570:32)
remote:        at Object.Module._extensions..js (module.js:579:10)
remote:        at Module.load (module.js:487:32)
remote:        at tryModuleLoad (module.js:446:12)
remote:        at Function.Module._load (module.js:438:3)
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - A module may be missing from 'dependencies' in package.json
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked-dependencies
remote:
remote:        - This module may be specified in 'devDependencies' instead of 'dependencies'
remote:        https://devcenter.heroku.com/articles/nodejs-support#devdependencies
remote:
remote:        - This project was built with yarn, which is new and under development. Some projects can still be built more reliably with npm
remote:        https://devcenter.heroku.com/articles/nodejs-support#build-behavior
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to commandiv-3.
remote:
To https://git.heroku.com/commandiv-3.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/commandiv-3.git'
```

**Comment by tgoldenberg** [comment]
looks like it was using `yarn` over `npm`
