### ISSUE TITLE
Does not seem to support loading `.css` files from `node_modules`

### ISSUE THREAD

**Issue by cubodehelio** [davibe/next.js-example-with-global-stylesheet#2]
I'm trying to load [normalize.css](https://necolas.github.io/normalize.css/) from `node_modules` and it give me the following error

```
SyntaxError: Unexpected token {
/home/cubodehelio/next.js-css-global-style-test/node_modules/normalize.css/normalize.css:13
html {
     ^
SyntaxError: Unexpected token {
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/cubodehelio/next.js-css-global-style-test/.next/dist/pages/index.js:15:18)
    at Module._compile (module.js:570:32)
```

Even if I explicitly include `node_modules` in `next.config.js`:

```js
{
        test: /\.css$/,
        loader: "babel-loader!raw-loader",
        include: ['node_modules/normalize.css', 'pages']
}
```

I don't know if is a matter of this example or an issue with [babel-plugin-wrap-in-js](https://github.com/davibe/babel-plugin-wrap-in-js).

I will move third party styles to the `pages/` folder in the mean time. Thanks for your work!

**Comment by davibe** [comment]
I just tried. You have to refer to it explicitly, i.e.

```javascript
import normalize from '../node_modules/normalize.css/normalize.css'
```

I understand this is not ideal but it's still reasonable comprated to not having this at all :)
